quarkus.log.level=INFO

# Jlama LLM Configuration (Quarkus LangChain4j Extension)
quarkus.langchain4j.jlama.chat-model.model-name=tjake/Llama-3.2-1B-Instruct-JQ4
quarkus.langchain4j.jlama.chat-model.temperature=0.3
quarkus.langchain4j.jlama.chat-model.max-tokens=512

quarkus.langchain4j.jlama.log-requests=true
quarkus.langchain4j.jlama.log-responses=true

# HTTP
quarkus.http.port=8080
