---

# - name: User workload monitoring
#   ansible.builtin.include_tasks: user_workload_monitoring.yml

# - name: Install OpenShift Gitops
#   ansible.builtin.include_tasks: openshift_gitops.yml


# - name: Install RHBK
#   ansible.builtin.include_tasks: rhbk.yml

- name: Install OpenShift Serverless
  ansible.builtin.include_tasks: serverless.yml


- name: Deploy Globex application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-application.yaml.j2') }}"
  vars:
    r_workload_quarkus_sentiment_analysis_globex_namespace: "globex-user"
    r_workload_quarkus_sentiment_analysis_globex_mw_namespace: "globex-mw-user"


- name: Deploy Globex application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-application.yaml.j2') }}"
  vars:
    r_workload_quarkus_sentiment_analysis_globex_namespace: "globex-user"
    r_workload_quarkus_sentiment_analysis_globex_mw_namespace: "globex-mw-user"



- name: Deploy Globex application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'serverless-application.yaml.j2') }}"
  vars:
    r_workload_quarkus_sentiment_analysis_globex_namespace: "globex-user"
    r_workload_quarkus_sentiment_analysis_globex_mw_namespace: "globex-mw-user"

