---
- name: "Create user namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_namespaces:
      - name: "globex-user"
        managedByArgo: "{{ globex-gitops }}"
      - name: "globex-mw-user"
        managedByArgo: "{{ globex-gitops }}"
      - name: "{{ globex-gitops }}"
        managedByArgo: ""
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings:
      - namespace: "globex-user"
        role: "admin"
      - namespace: "globex-mw-user"
        role: "admin"
      - namespace: "{{ globex-gitops }}"
        role: "admin"
  retries: 10
  delay: 30

- name: Deploy applicationset
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'applicationset.yaml.j2') | from_yaml }}"

- name: "Give argocd serviceaccounts access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding-argo.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings_argo:
      - namespace: "globex-user"
        role: "admin"
      - namespace: "globex-mw-user"
        role: "admin"
  retries: 10
  delay: 30

- name: Deploy Globex application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-application.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_globex_namespace: "globex-user"
    r_cloud_architecture_workshop_globex_mw_namespace: "globex-mw-user"
