---

- name: User workload monitoring
  ansible.builtin.include_tasks: user_workload_monitoring.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml


- name: Install RHBK
  ansible.builtin.include_tasks: rhbk.yml



- name: Install Sentiment Analusis App
  ansible.builtin.include_tasks: application.yml
